# Generated by Django 5.1.15 on 2026-04-28 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='otpcode',
            new_name='accounts_ot_phone_573c27_idx',
            old_name='accounts_ot_phone_purpose_idx',
        ),
        migrations.AlterField(
            model_name='totpdevice',
            name='is_confirmed',
            field=models.BooleanField(default=False, help_text='True once the user has scanned + verified the first code.'),
        ),
        migrations.AlterField(
            model_name='totpdevice',
            name='last_used_counter',
            field=models.BigIntegerField(default=0, help_text='Unix timestamp of last accepted code — prevents replay.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
