# Generated by Django 5.0.1 on 2026-05-22 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_email_alter_user_phone'),
        ('laboratories', '0003_alter_laboratory_opening_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='staffprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('user', 'laboratory'), name='uniq_staff_user_lab'),
        ),
    ]
