# Generated by Django 5.0.1 on 2026-06-05 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_trusteddevice'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='trusteddevice',
            new_name='accounts_tr_phone_df3b46_idx',
            old_name='accounts_tr_phone_8a1f3c_idx',
        ),
    ]
