# Generated by Django 5.0.1 on 2026-04-30 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='testcatalogentry',
            new_name='analyses_te_laborat_66cc20_idx',
            old_name='catalog_lab_active_idx',
        ),
        migrations.RenameIndex(
            model_name='testorder',
            new_name='analyses_te_status_8f3463_idx',
            old_name='order_status_idx',
        ),
        migrations.AlterField(
            model_name='sample',
            name='collected_by',
            field=models.ForeignKey(blank=True, help_text='Infirmier·e ou secrétaire ayant fait le prélèvement.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples_collected', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sample',
            name='received_by',
            field=models.ForeignKey(blank=True, help_text="Technicien·ne ayant réceptionné l'échantillon.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testcatalogentry',
            name='code',
            field=models.CharField(db_index=True, help_text='Code interne du test (ex: NFS, GLY, TSH).', max_length=40),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='value',
            field=models.CharField(help_text='Valeur mesurée (texte/numérique).', max_length=120),
        ),
    ]
