# Generated by Django 5.0.1 on 2026-04-30 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='appointment',
            new_name='appointment_laborat_a57603_idx',
            old_name='appt_lab_sched_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='appointment_patient_ce499b_idx',
            old_name='appt_pat_sched_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='appointment_assigne_688012_idx',
            old_name='appt_nurse_sched_idx',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='assigned_nurse',
            field=models.ForeignKey(blank=True, help_text='Infirmier·e affecté·e à la visite à domicile.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_visits', to=settings.AUTH_USER_MODEL),
        ),
    ]
