# Generated by Django 5.1.15 on 2026-04-28 00:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratory',
            name='emergency_fee_mru',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Frais supplémentaires pour une prise en charge urgente (MRU).', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='home_visit_fee_mru',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Frais supplémentaires pour un prélèvement à domicile (MRU).', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='opening_hours',
            field=models.JSONField(default={'fri': {'close': '18:00', 'closed': False, 'open': '08:00'}, 'mon': {'close': '18:00', 'closed': False, 'open': '08:00'}, 'sat': {'close': '13:00', 'closed': False, 'open': '08:00'}, 'sun': {'closed': True}, 'thu': {'close': '18:00', 'closed': False, 'open': '08:00'}, 'tue': {'close': '18:00', 'closed': False, 'open': '08:00'}, 'wed': {'close': '18:00', 'closed': False, 'open': '08:00'}}, help_text='Horaires par jour. Ex: {"mon": {"open": "08:00", "close": "18:00", "closed": false}}'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='technician_mode',
            field=models.CharField(choices=[('separate', 'Technicien distinct du biologiste'), ('merged_with_biologist', 'Technicien fusionné avec le biologiste')], default='separate', help_text="Certains labos n'ont pas de technicien dédié : le biologiste saisit lui-même les valeurs. Configurable par labo.", max_length=32),
        ),
    ]
