# Generated by Django 5.0.1 on 2026-04-29 20:12

import laboratories.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratories', '0002_alter_laboratory_emergency_fee_mru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratory',
            name='opening_hours',
            field=models.JSONField(default=laboratories.models.default_opening_hours, help_text='Horaires par jour. Ex: {"mon": {"open": "08:00", "close": "18:00", "closed": false}}'),
        ),
    ]
