# Generated by Django 5.0.1 on 2026-06-05 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='inventoryitem',
            new_name='inventory_i_laborat_ab2e4b_idx',
            old_name='inventory_i_laborat_5b7a6f_idx',
        ),
        migrations.RenameIndex(
            model_name='inventorymovement',
            new_name='inventory_i_item_id_bb3fe6_idx',
            old_name='inventory_m_item_id_1f8e25_idx',
        ),
    ]
